### ISSUE TITLE
Calculer des improve conditions

### ISSUE THREAD

**Issue by ttben** [ttben/pfe-ecoknowledge#25]

**Comment by PETILLON-Sebastien** [comment]
Stupid faggot your are Seb -> Custom deserializer please because you're receiving "lastMonth" and you have to generate a TimeBox with that ... 

-> That's ok bow

**Comment by PETILLON-Sebastien** [comment]
How to improve that ? 
- make the comparizon week end a friday (really not important)
- Don't work from the interface ("Relever !")
- Check the broken test
